volumes:
  data:

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=hQ4SmC4H
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql
  myapp:
    image: [YOUR-APP-IMAGE]